### ISSUE TITLE
LaziImageFull.d.ts errors

### ISSUE THREAD

**Issue by wrench7** [fpapado/react-lazy-images#12]
I've just installed v1.1 and noticed that there's now a bunch of TS errors in IntelliJ, complaining about the LazyImageFull.d.ts file.

Error:(80, 41) TS1005: ',' expected.
Error:(81, 17) TS1005: ',' expected.
Error:(82, 18) TS1005: ',' expected.
Error:(83, 16) TS1005: ',' expected.
Error:(84, 20) TS1005: ',' expected.
Error:(86, 20) TS1005: ',' expected.
Error:(87, 6) TS1005: ',' expected.
Error:(89, 17) TS1005: ',' expected.
Error:(90, 18) TS1005: ',' expected.
Error:(91, 16) TS1005: ',' expected.
Error:(92, 20) TS1005: ',' expected.
Error:(94, 20) TS1005: ',' expected.
Error:(95, 6) TS1005: ',' expected.
Error:(96, 10) TS1109: Expression expected.
Error:(96, 18) TS1109: Expression expected.
Error:(102, 29) TS1005: ',' expected.
Error:(104, 24) TS1005: ',' expected.
Error:(105, 6) TS1005: ',' expected.
Error:(106, 23) TS1005: ',' expected.
Error:(107, 20) TS1005: ',' expected.
Error:(109, 20) TS1005: ',' expected.
Error:(110, 6) TS1005: ',' expected.
Error:(113, 24) TS1005: ',' expected.
Error:(114, 6) TS1005: ',' expected.
Error:(115, 23) TS1005: ',' expected.
Error:(116, 20) TS1005: ',' expected.
Error:(118, 20) TS1005: ',' expected.
Error:(119, 6) TS1005: ',' expected.
Error:(120, 10) TS1109: Expression expected.
Error:(120, 18) TS1109: Expression expected.
Error:(80, 35) TS2304: Cannot find name 'import'.
Error:(80, 54) TS2339: Property 'Unionized' does not exist on type '"unionize"'.
Error:(86, 14) TS2693: 'string' only refers to a type, but is being used as a value here.
Error:(88, 23) TS2339: Property 'MultiValueVariants' does not exist on type 'Promise<typeof "C:/Projects/_experiments/Q-view-react/node_modules/unionize/lib/index">'.
Error:(94, 14) TS2693: 'string' only refers to a type, but is being used as a value here.
Error:(102, 23) TS2304: Cannot find name 'import'.
Error:(102, 42) TS2339: Property 'Unionized' does not exist on type '"unionize"'.
Error:(104, 17) TS2693: 'boolean' only refers to a type, but is being used as a value here.
Error:(109, 14) TS2693: 'string' only refers to a type, but is being used as a value here.
Error:(111, 23) TS2339: Property 'MultiValueVariants' does not exist on type 'Promise<typeof "C:/Projects/_experiments/Q-view-react/node_modules/unionize/lib/index">'.
Error:(113, 17) TS2693: 'boolean' only refers to a type, but is being used as a value here.
Error:(118, 14) TS2693: 'string' only refers to a type, but is being used as a value here.

Not sure if you're seeing the same issues that end, but IntelliJ wasn't complaining with the previous version.

I've also had to upgrade my @types/react typedefs as the linter was complaining about the usage of React.RefObject

**Comment by fpapado** [comment]
Hmm, I'm not at the computer atm to debug, but definitely odd errors. The way Typescript handles types of deps leaves something to be desired, so it's probably there.

Some questions to narrow it down a bit:
- Does a build from the CLI / your build setup work? I.e. Is it just IntelliJ/the IDE that fails?
- What Typescript version are you on? I wonder if pre-2.8 or pre-2.9 versions fail. The reason would be that the way types from imports are referenced has changed (can't remember the exact TS version that did it). I can think of a few ways to mitigate that if that's is the case.

**Comment by wrench7** [comment]
The build works, so it's only the IDE that's complaining (though the errors look legit to me).
I'm on Typescript 2.6.2. Should I bump it and see if that fixes the errors?

**Comment by fpapado** [comment]
Yup, bumping TS might show some unrelated errors in the codebase, but it can give us some good data points anyway.

Another thing you can check is whether the IDE is using a different TS version from the build. I am not familiar with IntelliJ, but I know that VS Code sometimes breaks in similar ways because it uses its own TS by default.

**Comment by wrench7** [comment]
I've just updated my react and react-dom versions along with @types/react and @types/react-dom. That fixed the React.RefObject issues. Upgrading Typescript to 3 appears to have solved all the other errors. 
Closing this one now.
