### ISSUE TITLE
Images not loading in ios safari 

### ISSUE THREAD

**Issue by JoshuaHuber** [fpapado/react-lazy-images#15]
Thanks for your work on this.  It works great on the desktop but doesn't work on ios safari.

**Comment by fpapado** [comment]
Hi, @JoshuaHuber! 

The first thing that comes to mind, have you added the polyfill for IntersectionObserver? 

**If not:**
Safari does not implement the IntersectionObserver API at the moment, so you have to add a polyfill. The IntersectionObserver API is modern and very efficient, and the polyfill falls back to more established behaviour. The ["Polyfilling IntersectionObserver" section of the docs](https://github.com/fpapado/react-lazy-images#polyfill-intersectionobserver) has all the data you might need; usage statistics, bundle size effects, a couple of strategies and links to the relevant source code, if you are curious what it does.

**If you have added the polyfill and it doesn't work:**
I am curious what the failure is. Is there anything written on the console? What version of Safari are you on?

Regarding it working on desktop, is that desktop Safari, or some other browser? If you haven't added the polyfill, then it shouldn't be working on desktop Safari either.

Hope this helps, let me know if you make any progress :)

**Comment by JoshuaHuber** [comment]
@fpapado Thanks for the help reading. lol.  It's working great!
