### ISSUE TITLE
Last Chrome version keeps NotAsked state

### ISSUE THREAD

**Issue by aralroca** [fpapado/react-lazy-images#27]
In Firefox and Safari is working correctly. However I can't say the same using my `Chrome Version 75.0.3770.100`.

Using a carousel, or just scrolling, the images are not detected as visibles. Displaying always the placeholder, in my case; `<div class="img-loading"></div>`... The only way that I have to force to print the image, is doing resize of the window.

![carousel](https://user-images.githubusercontent.com/13313058/60251650-38c82500-98c9-11e9-83a3-3927067f0625.gif)

My current image component:

```jsx
 <LazyImage
  src={src}
  {...altAndTitle}
  actual={({ imageProps }) => (
    <img
       draggable={false}
        {...imageProps}
        {...props}
      />
   )}
   error={() => (
       <img
          className="error-img"
           {...props}
            src={fallbackSrc}
         />
     )}
   placeholder={({ ref }) => <div className="img-loading" ref={ref} />}
/>
```

**Comment by aralroca** [comment]
I guess this is happening in the new Chrome versio, after this Chrome feature: 

IntersectionObserver V2:

* https://www.chromestatus.com/feature/5878481493688320

**Comment by aralroca** [comment]
Looks that the InView have the `inView` state as `false` although the image is in the viewport...

![image](https://user-images.githubusercontent.com/13313058/60589118-fc00a000-9d98-11e9-8998-3bd9698bbbd3.png)

**Comment by fpapado** [comment]
Hi, @aralroca ! Sorry for the late reply, I've had my hands full lately.
One thing I'm noticing in that inspector screenshot is that the height of the image is 0px. I'm wondering if that somehow affects the "in view" calculation. Could you try giving the `.img-loading` class some height and checking if that helps? Usually setting a width/height (even minimums, or placeholders) has done the trick in a couple of cases I've had.

If that doesn't help, we can keep looking :)

**Comment by aralroca** [comment]
@fpapado wuau, I didn't see it! You solved the problem with just one comment! Thank you so much, changing the height is solving the problem.

This before in Chrome was working fine, and other browsers as firefox or safari, but make sense to have some height to be visible!
