### ISSUE TITLE
Downloading images twice

### ISSUE THREAD

**Issue by aralroca** [fpapado/react-lazy-images#32]
When the placeholder is visible on the viewport is downloading the image twice, at the same time.

![image](https://user-images.githubusercontent.com/13313058/72714975-ec4b7c00-3b6f-11ea-93e4-a1701fd9bd98.png)

I debugged my app to see why this is happening, and I see that If I replace that Promise to just a Promise.resolve(), it is working downloading the image only once:

https://github.com/fpapado/react-lazy-images/blob/master/src/LazyImageFull.tsx#L366

What's the reason for downloading twice the image? I suppose that the second download is after replacing the placeholder with the `img` tag.  Is this under control?

**Comment by egemon** [comment]
Had the same issue - moved with https://www.npmjs.com/package/react-intersection-observer

**Comment by adshrc** [comment]
@egemon can you please explain this?

**Comment by adshrc** [comment]
Guys, disable your dev tools cache. It makes sense that the image is loaded twice while the cache is disabled 🙄 After enabling cache again, everything works as expected

**Comment by aralroca** [comment]
Ok. I'm going to close this.
