### ISSUE TITLE
Support for components other than images

### ISSUE THREAD

**Issue by oyeanuj** [fpapado/react-lazy-images#6]
Hi @fpapado, thank you for open-sourcing this library! I am wondering what your thoughts are around making this library work for more than just images? 

Image is a special-case, and since you've already solved the harder one, would you be open to offering a component that lazy loads any child (and not just image)?

**Comment by fpapado** [comment]
Hi, @oyeanuj!

Thanks for getting in touch. I have been thinking about this issue for the past few days.

**The short answer is that I think loading generic components is out of scope for this project. I hope that the long answer can explain the reasoning and perhaps even offer viable ideas :)**

There are two things that go into lazy-loading X thing:
1. Deciding when to load the thing
2. Figuring out how to load it

**Part (1) in this case would be "load the thing whenever it is in the viewport".**

This part can probably shared for any "Lazy X loading" task. I really like the performance that [IntersectionObserver](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) offers. This library, for instance, uses [`react-intersection-observer`](https://github.com/thebuilder/react-intersection-observer) exactly for that part. Its API has been really flexible and simple; I would definitely recommend it for lazy-loading tasks.

If you're making a library, [make sure to instruct users to polyfill](https://github.com/thebuilder/react-intersection-observer#intersection-observer), or do so if you are building an app.

**Then we get to part (2), actually loading.**

For images, there are a few nuances, such as preloading before swapping, offering placeholders, passing on image attributes etc. The API is flexible, but the implementation and patterns are still very much about loading images (the React components that consume them are eagerly loaded).

There are also a number of image-specific techniques I would like to apply in the future, such as decoding off-main-thread before declaring as 'loaded'.

For *loading components*, there are different considerations, such as module loading (dynamic ES imports + some loader system), keeping track of their location, and other things for server-side rendering. These concerns are much closer to the application level than images.

Two libraries I often see for this purpose:
- https://github.com/jamiebuilds/react-loadable
- https://github.com/smooth-code/loadable-components

Both of those libraries seem to require some application-level setup. I think it might be hard to wrap them up in another library, or that maintaining the docs/hierarchy would be tiresome. However, keeping in mind (1) and (2), I think composition at the application- level would be a fantastic idea!

Composing the detecting and loading strategies could look something like this:
https://codesandbox.io/s/3v0p851526

(Note that Codesandbox is not really "lazy" loading anything in that example. Could be me messing something up.)

Long answer, but I hope this helps!
